### ISSUE TITLE
Error: robot.urdf.xacro could not be found

### ISSUE THREAD

**Issue by dakuhn** [SammyRamone/sw2urdf_ros2#1]
Hi Sammy, 

thank you very much for this script! It helps me a lot!

I have the error that the file robot.urdf.xacro could not be found after the build when I run the startup file.
If I manually rename the file in the installation folder, it works.

Now I have added line 105 and it also works with the script:
![image](https://github.com/SammyRamone/sw2urdf_ros2/assets/5545470/e9711e0f-2dfa-43fd-ad5b-485b0cb31325)

I work with ROS2 Humble.
Maybe someone else has the same problem and it helps.

All the best, 
Daniel

**Comment by SammyRamone** [comment]
Thanks for reporting this bug and the solution. The latest commit should fix it.
